namespace ContactManager.Models
{
    public class Category
    {
        // primary key - generated by database

        //Step 2: add properties here
        public int CategoryId { get; set; }
        public string Name { get; set; }

    }
}
